language: java
notifications:
  hipchat:
    rooms:
      secure: cHbJQriYfA8uq3ylCMlXmNppwM9+rjMGxmux2A6MIPWvRY0wMqpUGWbdW6kscT56Fzi6hODLHL13MvEC18qnLGIVwZI1lYG2yrD+TKoi3jy2Vn0akx6IEzmCnOC4CqrwltJ7JO5XJTr0el7RP5x4OH3P4YDkVXKqHqFsqR0b8tQ3xl887XnJjxPyJRJvqNkGniokSOholpmJRfglmZDTURwgk9bXH7hwakx14n0IMVDpfbus+X/Wk/nRb2acbTFMOEc9yVNuQ8MTGmNpQdk36PsH+31Xej4WulUq+cEv6tYqgXQQ0EA8zQ7OKOI/pXViaXZWepValq+bJKK0lqw3g252qeU4XDpGIEdfuxYaSuy1zmVZK9v2gQgN0pvPOodKpnNELEDahBfboGdvvYGX4RjdyHZyGeDaWLB8FiiXdo8s9Ok04qbk1GAZ6KYY8oQHChx5Ln01sYQFBPqb28Onl//ir5bIRkQ7+2QGSulE4bi+9yZLMsOvFsZLQBmaApJs3OZvtZWJC0u0PHNVDEx1QIp5mFs75Y0GewGXomoIlkUFk4VoXeTuNGOQ5NO3VtXO7NQqbnottsgZUeGE7/ic2VUXts6lwZFNI0D9SuWv9Qd+eKWOu/iIPTRpeKytVA9XVYEogETop01B+R0zEB5dSbnQOoAc2rI84kIn1AugiUw=
deploy:
  provider: releases
  api_key:
    secure: HigQ/W/OL1KINOSADbCGnpxbtd/MuwIs0MTkgO1dCbgnm7s47snuQ33EMgb38Z9bfur/ryyfJukrUD0oOt8pfAqlqlBJFLXM5G9oi0yqbHraa6vLdXmRS60FVkk9/d3xZRbgJaMvr2kP6huSIeJyg6bcyBrKtltddrsVCILgmiytgl2g27BW2C2VW3RuxIFz711J6x2rbSreQnAonj2vYMkhW5tukLfxs7TDLnvusR9o3yl9W+LoLvKh62mj20vaT7yw0wmq+WDYjoAOkEJnxvTg8VMVpaXf1QuRgasA1hfC0QvzR/nHsqzL5CNu+NyZ+viNyhjqTpKvWAUVeGx5vV4R53tz0FIVavTnma0M0c+XzBEmCn+4SHWN03fRQ8UT3qyOguegiQY8/wD/pZr1Pz607ppmkfPnR8AJqndOokf043+A7s0SLwrrXi+L+Jl1FuEnVXisjwc2OI74M5da41IA5Y+T6F4Lm+MmPt1q/KVAUj3LR5L0jWAQieKTLkQWgEbK8AB4JDO7mj8ghVVZ/Cq1TRS/0+FwJFJg2ngj2oD4EYh4eDfRXHbMFoFBGtvAxL7/EATRNuIeZeeKPWpkUghnb7xNCCpYVGaHM4QELYV2UC6aMPZsu8CkmpYkOn6aQiqXKGySSsifIpcHG6SmZZGStFuebmjs/uF/QBnwyeg=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-sonar-plugin
