language: java
jdk: openjdk8
notifications:
  slack:
    secure: gzILkT2roqAKpL/SsRQQklP5XNx9gBcGnoQbdU4KA7lytA3ymUaBCNHGMw3YGuyDYBSbRbo5GT0lVjdcWDghpC6LB//pWsaMBtfEY4Aw+eamuaQaLMOJWjNr1t+JIsCT7eFDwoQLi462PNDbYb3f8J61MalGtczw49th59RTgsE6PfwZVgwY8qAl2yh7Zj8KDfg2n0Ta51J6FPN+YoFu27fI8ZzWEZd9FjgdQlXp1JEq76e9lW8Dg4/nMKIaw6kL4/LVCMOqGxNZIuylP0AIP738kzi0QgHHUuU/I6T2rXUNfll9tAOZi3GpP+Fxoyv7RzE3ZSnlTOR5+fbC2kYIlqWZkbsg1vPN4Qft0/Uz644WVj5bvQU1RclTKL5l9LUhmxi16DHZsRLA1MjNG2Wl7SIM0Uf8QoysbSYeb5QBqLy+VePCNU972gPVldc4wTu8QbZTZyiDv0buquNEFk0CWrNcZURjPVnnblsiToHAV2PGRKFx8UZ6uZCejGnB6UdEq79QnjSB4+ALllXIyCzFNbqRjB8JHG4xbYZjXp0eZWAf+I8VhWuhbs23EmPHAR9lCDawotm96c7foSeioeI44zR8kFmPOaPKCs32o3PYsiu9XbpuU1TqrASfIXjbEpK5cTJxRg5cqCLpUmrG7XW/wmP828isUzNVziAkN6QIryQ=
deploy:
  provider: releases
  api_key:
    secure: HigQ/W/OL1KINOSADbCGnpxbtd/MuwIs0MTkgO1dCbgnm7s47snuQ33EMgb38Z9bfur/ryyfJukrUD0oOt8pfAqlqlBJFLXM5G9oi0yqbHraa6vLdXmRS60FVkk9/d3xZRbgJaMvr2kP6huSIeJyg6bcyBrKtltddrsVCILgmiytgl2g27BW2C2VW3RuxIFz711J6x2rbSreQnAonj2vYMkhW5tukLfxs7TDLnvusR9o3yl9W+LoLvKh62mj20vaT7yw0wmq+WDYjoAOkEJnxvTg8VMVpaXf1QuRgasA1hfC0QvzR/nHsqzL5CNu+NyZ+viNyhjqTpKvWAUVeGx5vV4R53tz0FIVavTnma0M0c+XzBEmCn+4SHWN03fRQ8UT3qyOguegiQY8/wD/pZr1Pz607ppmkfPnR8AJqndOokf043+A7s0SLwrrXi+L+Jl1FuEnVXisjwc2OI74M5da41IA5Y+T6F4Lm+MmPt1q/KVAUj3LR5L0jWAQieKTLkQWgEbK8AB4JDO7mj8ghVVZ/Cq1TRS/0+FwJFJg2ngj2oD4EYh4eDfRXHbMFoFBGtvAxL7/EATRNuIeZeeKPWpkUghnb7xNCCpYVGaHM4QELYV2UC6aMPZsu8CkmpYkOn6aQiqXKGySSsifIpcHG6SmZZGStFuebmjs/uF/QBnwyeg=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-sonar-plugin
